In [1]:
# Pacote é usado para gravar as versões de outro pacotes neste jupyter notebook
!pip install -q -U Watermark

In [2]:
# import
import numpy as np

In [3]:
import warnings
warnings.filterwarnings ('ignore')

In [5]:
# Versões dos pacotes usados 
%reload_ext watermark
%watermark -a "Danilo Mendes" --iversions

Author: Data Science Academy

numpy: 1.18.1



In [6]:
# configuração de impressão do Numpy
np.set_printoptions(suppress = True, linewidth = 200, precision =2)

https://numpy.org/doc/stable/reference/generated/numpy.set_printoptions.html

Carregando o DataSet

In [9]:
dados = np.genfromtxt("dados/dataset1.csv",
                     delimiter = ';',
                     skip_header = 1,
                      autostrip = True,
                     encoding = 'cp1252')

In [10]:
type(dados)

numpy.ndarray

In [11]:
dados.shape

(10000, 14)

In [13]:
dados.view()

array([[48010226.  ,         nan,    35000.  , ...,         nan,         nan,     9452.96],
       [57693261.  ,         nan,    30000.  , ...,         nan,         nan,     4679.7 ],
       [59432726.  ,         nan,    15000.  , ...,         nan,         nan,     1969.83],
       ...,
       [50415990.  ,         nan,    10000.  , ...,         nan,         nan,     2185.64],
       [46154151.  ,         nan,         nan, ...,         nan,         nan,     3199.4 ],
       [66055249.  ,         nan,    10000.  , ...,         nan,         nan,      301.9 ]])

Verificando valores Ausentes

In [14]:
np.isnan(dados).sum()

88005

In [24]:
valor_coringa = np.nanmax(dados) + 1
print (valor_coringa)

68616520.0


In [27]:
# media variaveis numericas
media_ignorando_nan = np.nanmean(dados, axis = 0)
print(media_ignorando_nan)

[54015809.19         nan    15273.46         nan    15311.04         nan       16.62      440.92         nan         nan         nan         nan         nan     3143.85]


In [29]:
# Colunas do tipo string com valores ausentes
colunas_string = np.argwhere(np.isnan(media_ignorando_nan)).squeeze()
colunas_string

array([ 1,  3,  5,  8,  9, 10, 11, 12], dtype=int64)

In [30]:
# Colunas numericas
colunas_numerica = np.argwhere(np.isnan(media_ignorando_nan) == False).squeeze()
colunas_numerica

array([ 0,  2,  4,  6,  7, 13], dtype=int64)

In [32]:
# Carregar novamente os dados porque temos muitos valores na
# carrega as colunas do tipo string
arr_strings = np.genfromtxt("dados/dataset1.csv",
                           delimiter = ';',
                           skip_header = 1,
                           autostrip = True,
                           usecols = colunas_string,
                           dtype = str,
                           encoding = 'cp1252')

In [33]:
arr_strings

array([['May-15', 'Current', '36 months', ..., 'Verified', 'https://www.lendingclub.com/browse/loanDetail.action?loan_id=48010226', 'CA'],
       ['', 'Current', '36 months', ..., 'Source Verified', 'https://www.lendingclub.com/browse/loanDetail.action?loan_id=57693261', 'NY'],
       ['Sep-15', 'Current', '36 months', ..., 'Verified', 'https://www.lendingclub.com/browse/loanDetail.action?loan_id=59432726', 'PA'],
       ...,
       ['Jun-15', 'Current', '36 months', ..., 'Source Verified', 'https://www.lendingclub.com/browse/loanDetail.action?loan_id=50415990', 'CA'],
       ['Apr-15', 'Current', '36 months', ..., 'Source Verified', 'https://www.lendingclub.com/browse/loanDetail.action?loan_id=46154151', 'OH'],
       ['Dec-15', 'Current', '36 months', ..., '', 'https://www.lendingclub.com/browse/loanDetail.action?loan_id=66055249', 'IL']], dtype='<U69')